/**
 * PDF Generation Utility
 * Uses PDFKit to generate PDFs server-side without requiring Puppeteer/Chrome
 * This is more reliable on Vercel's serverless environment
 */

import PDFDocument from 'pdfkit';

interface SessionData {
  title: string;
  ageGrade: string;
  gender: string;
  playerCount: number;
  abilityLevel: string;
  sessionLength: number;
  topic: string;
  principle: string;
  struggles?: string | undefined;
  desiredOutcome?: string | undefined;
  contactLevel: string;
  equipment?: string | undefined;
  space?: string | undefined;
  planMarkdown: string;
  createdAt: string;
}

export async function generateSessionPDF(session: SessionData): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    try {
      const doc = new PDFDocument({
        size: 'A4',
        margin: 40,
        bufferPages: true,
      });

      const chunks: Buffer[] = [];

      doc.on('data', (chunk: Buffer) => {
        chunks.push(chunk);
      });

      doc.on('end', () => {
        resolve(Buffer.concat(chunks));
      });

      doc.on('error', (err: Error) => {
        reject(err);
      });

      // Add content to PDF
      addContentToPDF(doc, session);

      // Finalize PDF
      doc.end();
    } catch (error) {
      reject(error);
    }
  });
}

// eslint-disable-next-line @typescript-eslint/no-explicit-any
function addContentToPDF(doc: any, session: SessionData): void {
  const formattedDate = new Date(session.createdAt).toLocaleDateString('en-GB', {
    year: 'numeric',
    month: 'long',
    day: 'numeric',
  });

  // Register fonts
  doc.registerFont('Helvetica', 'Helvetica');
  doc.registerFont('Helvetica-Bold', 'Helvetica-Bold');

  // Header section with background
  doc.rect(0, 0, doc.page.width, 120).fill('#0D1B3E');
  
  // Logo and title
  doc.fillColor('#84CC16');
  doc.fontSize(16).font('Helvetica-Bold').text('🏉 RUGBY PRACTICE PLANNER', 40, 20);
  
  doc.fillColor('#FFFFFF');
  doc.fontSize(24).font('Helvetica-Bold').text(session.title, 40, 45);
  
  doc.fillColor('#CBD5E1');
  doc.fontSize(11).font('Helvetica').text(`Session Plan • Created ${formattedDate}`, 40, 75);

  // Move past header
  doc.moveDown(5);

  // Session Details Grid
  doc.fillColor('#F8FAFC');
  doc.rect(40, doc.y, doc.page.width - 80, 140).fill();
  
  doc.fillColor('#0D1B3E');
  const detailsStartY = doc.y + 10;
  const colWidth = (doc.page.width - 80) / 2;
  
  const details = [
    { label: 'Age Grade', value: session.ageGrade },
    { label: 'Players', value: session.playerCount.toString() },
    { label: 'Ability Level', value: session.abilityLevel },
    { label: 'Duration', value: `${session.sessionLength} minutes` },
    { label: 'Topic', value: session.topic },
    { label: 'Principle', value: session.principle },
    { label: 'Contact Level', value: session.contactLevel },
    { label: 'Gender', value: session.gender },
  ];

  let row = 0;
  let col = 0;
  
  for (const detail of details) {
    const x = 50 + col * colWidth;
    const y = detailsStartY + row * 35;

    doc.fontSize(9).font('Helvetica-Bold').fillColor('#64748B');
    doc.text(detail.label.toUpperCase(), x, y);
    
    doc.fontSize(12).font('Helvetica').fillColor('#1E293B');
    doc.text(detail.value, x, y + 15);

    col++;
    if (col === 2) {
      col = 0;
      row++;
    }
  }

  doc.moveDown(6);

  // Additional sections
  if (session.struggles) {
    addSection(doc, 'Player Struggles', session.struggles);
  }

  if (session.desiredOutcome) {
    addSection(doc, 'Desired Outcome', session.desiredOutcome);
  }

  if (session.equipment) {
    addSection(doc, 'Equipment', session.equipment);
  }

  if (session.space) {
    addSection(doc, 'Space', session.space);
  }

  // Session Plan
  addSection(doc, 'Session Plan', formatPlanMarkdown(session.planMarkdown));

  // Footer
  doc.moveDown(2);
  doc.fillColor('#64748B');
  doc.fontSize(10).font('Helvetica');
  doc.text('Generated by Rugby Practice Planner', { align: 'center' });
  doc.fillColor('#84CC16');
  doc.fontSize(9).font('Helvetica-Bold');
  doc.text('Better Coaching. Better Players. Better Game.', { align: 'center' });
}

// eslint-disable-next-line @typescript-eslint/no-explicit-any
function addSection(doc: any, title: string, content: string): void {
  doc.moveDown(1);
  
  // Section title with underline
  doc.fillColor('#0D1B3E');
  doc.fontSize(14).font('Helvetica-Bold').text(title);
  
  // Underline
  const titleY = doc.y - 5;
  doc.strokeColor('#84CC16').lineWidth(2);
  doc.moveTo(40, titleY + 20).lineTo(doc.page.width - 40, titleY + 20).stroke();
  
  doc.moveDown(1);
  
  // Content
  doc.fillColor('#1E293B');
  doc.fontSize(11).font('Helvetica');
  doc.text(content, { width: doc.page.width - 80, align: 'left' });
}

function formatPlanMarkdown(markdown: string): string {
  // Simple markdown to text conversion
  return markdown
    .split('\n')
    .map(line => {
      // Remove markdown syntax
      return line
        .replace(/^#+\s+/, '') // Remove headings
        .replace(/\*\*(.*?)\*\*/g, '$1') // Remove bold
        .replace(/\*(.*?)\*/g, '$1') // Remove italics
        .replace(/^-\s+/, '• ') // Convert list items
        .trim();
    })
    .filter(line => line.length > 0)
    .join('\n');
}
